### ISSUE TITLE
Integrate BNS model training code

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframev2#125]

**Comment by EthanMarx** [comment]
I'll point you to the [frequency domain dataset](https://github.com/ML4GW/aframev2/blob/main/projects/train/train/data/supervised/frequency_domain.py). This is where q transform / spectrogram augmentations would go.  Also, the [frequency domain arch] (https://github.com/ML4GW/aframev2/blob/main/projects/train/train/architectures/supervised.py#L91) is a wrapper around ResNet2d that plays nicely with lightning.

Changing the [model arch class path](https://github.com/ML4GW/aframev2/blob/main/projects/train/config.yaml#L11) and [dataset class path](https://github.com/ML4GW/aframev2/blob/main/projects/train/config.yaml#L31) in the train config should get you started.
