### ISSUE TITLE
readme issue, apptainer image not in the directory

### ISSUE THREAD

**Issue by VasSkliris** [ML4GW/aframev2#145]
Main readme:

The repo to be git clones should be aframe2

Aframe Projects
"As an example, let's build the data container image. Once inside the data root directory, building the image is as simple as" 
There is no file in images at this point. So there is a disconection about how do these images get in there.

`apptainer build $AFRAME_CONTAINER_ROOT/data.sif apptainer.def
FATAL:   Unable to build from apptainer.def: unable to open file apptainer.def: open apptainer.def: no such file or directory
`

**Comment by EthanMarx** [comment]
Hi @VasSkliris, I am seeing the apptainer image in the data project root directory as advertised: https://github.com/ML4GW/aframev2/blob/main/projects/data/apptainer.def. 

Is this not getting pulled when you clone?

**Comment by VasSkliris** [comment]
Either it is not getting pulled, or I should have pulled aframe2 instead of aframe. The instruction mention aframe

**Comment by EthanMarx** [comment]
Also, make sure you  are cloning a fork of this repository!

**Comment by VasSkliris** [comment]
I was not doing that, I was just cloning it

**Comment by VasSkliris** [comment]
Hi @EthanMarx , so the code does not pull that blob directory. The image is inside project/data .... but the transfer from there to this newly created directory aframe/images is not clear when or how it happens. I still get the same error after the fork. 

After I fork and clone the repo I get a repo directory aframe2. When I create the AFRAME_CONTAINER_ROOT the instructions say ~/aframe/images which is a new directory (not inside aframe2) is that what supposed to happen?

**Comment by VasSkliris** [comment]
Update, the command works if you go in aframe/projects/data and run it from there but this is not clear from the instructions

**Comment by EthanMarx** [comment]
Looks like you need to make the `$AFRAME_CONTAINER_ROOT` directory. 

Yes the command assumes you are in the root of the `project` directory in this case, `/projects/data`. This is where we store the apptainer.def files for each project. 

I thought I had both of those clarified in the README, but I'll double check

**Comment by EthanMarx** [comment]
Specifically, [here](https://github.com/ML4GW/aframev2/blob/main/projects/README.md?plain=1#L25) and [here](https://github.com/ML4GW/aframev2/blob/main/projects/data/README.md?plain=1#L8)

**Comment by VasSkliris** [comment]
I see, I didn't go into individual instruction for each project (https://github.com/ML4GW/aframev2/blob/main/projects/README.md) I missed the instruction, it works now
