### ISSUE TITLE
missing generated directory

### ISSUE THREAD

**Issue by VasSkliris** [ML4GW/aframev2#159]
In https://github.com/VasSkliris/aframev2/blob/main/projects/data/README.md there is an aframe/data/train/background directory that is not created when the commands are run

**Comment by wbenoit26** [comment]
Did you create a `.env` file with [these](https://github.com/VasSkliris/aframev2/blob/813ed212adac890e3170ba65c61dac54675a0012/aframe/pipelines/sandbox/README.md?plain=1#L40) environment variables and run `source .env`?

**Comment by VasSkliris** [comment]
No this is before I go to the sandbox when I build the data project and then run all instructions in readme. I created the directory and it runs fine, I just think it misses from the commands that create directories possibly?

**Comment by wbenoit26** [comment]
Did you do this `mkdir` [here](https://github.com/VasSkliris/aframev2/blob/813ed212adac890e3170ba65c61dac54675a0012/projects/data/README.md?plain=1#L39)? Which command does this break on?

**Comment by VasSkliris** [comment]
Yes but there the command after this saves something in /aframe/data/train/background and that command does not create the background directory
