### ISSUE TITLE
Error handling when using 'H1', 'V1'  as ifo's

### ISSUE THREAD

**Issue by sjhend03** [ML4GW/aframev2#174]
Changed `L1` to `V1' in `sandbox.cfg` and added `v1` to `LigoResponseSet` and `LigoWaveformSet` and commented out `l1`, ran sandbox pipeline and returned,
`Traceback (most recent call last):
  File "/law_forward/py/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
  File "/law_forward/py/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
  File "/opt/aframe/aframe/tasks/data/waveforms.py", line 199, in run
    waveform_set = LVKWaveformSet(**parameters)
  File "<string>", line 24, in __init__
  File "/opt/aframe/libs/ledger/ledger/injections.py", line 225, in __post_init__
    InjectionMetadata.__post_init__(self)
  File "/opt/aframe/libs/ledger/ledger/injections.py", line 41, in __post_init__
    super().__post_init__()
  File "/opt/aframe/libs/ledger/ledger/ledger.py", line 52, in __post_init__
    raise ValueError(
ValueError: Field l1 has 0 entries, expected 50`

**Comment by wbenoit26** [comment]
Right, looks like we don't allow fields to have [different lengths](https://github.com/ML4GW/aframev2/blob/462c5094874d3a5eeaaada7b4d32fdaa1d905cd2/libs/ledger/ledger/ledger.py#L51). I think in general that's good behavior, but maybe the cleanest thing to do will be to allow fields of length 0, so just changing the linked line to `elif len(value) != _length and len(value) != 0:`. With that, we can just put whichever ifos we want in the `LVKResponseSet` class. Though, there may be other parts of the `Ledger` class and subclasses that expect equal-length arrays, so we should keep an eye out for other errors.

The alternative would be to have a function that creates a class based on a list of detectors. That would adhere more closely to the original idea of the object, but I think it would make them so cumbersome to use that it wouldn't be worth it.

**Comment by sjhend03** [comment]
I like the first idea, I'll run through the code with that method

**Comment by wbenoit26** [comment]
It looks like @EthanMarx has put together a PR (#175) that will handle this ledger generalization pretty nicely. I think keep doing what you're doing, but once that gets merged in you can switch over.

**Comment by sjhend03** [comment]
Perfect, sounds good.

**Comment by EthanMarx** [comment]
You will have to set the `AFRAME_REPO` environment variable to point to the location where you cloned `aframev2`

**Comment by sjhend03** [comment]
Sounds good thanks!

**Comment by EthanMarx** [comment]
@sjhend03 going to close this, but feel free to re-open other issues as they arise.
