### ISSUE TITLE
Error handling during `build-containers` doesn't work in all instances

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframev2#193]
Without the git installation mentioned in #192, the plots container was failing to build. However, this doesn't raise an exception [where we would expect it to](https://github.com/ML4GW/aframev2/blob/df2f27ef4fe2c6d7a1c5dae51c465cdf4767d11f/scripts/build_containers.py#L45), so the error doesn't get caught and we output that the plots container has been successfully built.

**Comment by EthanMarx** [comment]
@wbenoit26 This has been addressed right?

**Comment by wbenoit26** [comment]
Correct
