### ISSUE TITLE
Import error while trying to run sandbox pipeline

### ISSUE THREAD

**Issue by sjhend03** [ML4GW/aframev2#194]
While running sandbox pipeline I run into this error,
`Traceback (most recent call last):
  File "/opt/env/bin/law", line 10, in <module>
    exit_code = run()
  File "/law_forward/py/law/cli/cli.py", line 74, in run
    return mods[prog].execute(*exec_args)
  File "/law_forward/py/law/cli/run.py", line 57, in execute
    mod = __import__(modid, globals(), locals(), [cls_name])
  File "/home/stevenjames.henderson/aframev2/aframe/tasks/__init__.py", line 1, in <module>
    from .data import *
  File "/home/stevenjames.henderson/aframev2/aframe/tasks/data/__init__.py", line 14, in <module>
    from .timeslide_waveforms import *
  File "/home/stevenjames.henderson/aframev2/aframe/tasks/data/timeslide_waveforms/__init__.py", line 1, in <module>
    from .timeslide_waveforms import DeployTimeslideWaveforms, TimeslideWaveforms
  File "/home/stevenjames.henderson/aframev2/aframe/tasks/data/timeslide_waveforms/timeslide_waveforms.py", line 14, in <module>
    from utils import data as data_utils
ModuleNotFoundError: No module named 'utils'`

Also returning this error when trying to build the data container,
`singularity build --force /home/stevenjames.henderson/aframe/images/data.sif /home/stevenjames.henderson/aframev2/projects/data/apptainer.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
FATAL:   Unable to create build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
FATAL:   Unable to create build: while ensuring correct compression algorithm: while creating squashfs: create command failed: exit status 1: FATAL ERROR:Failed to create thread`

**Comment by wbenoit26** [comment]
The first error is coming from being unable to build the data container. I was getting the second error intermittently this afternoon on LLO, but it went away on its own, so it's a little tough to debug. From some old threads I'm finding online, I think it may be related to running out of RAM. Can you try re-building again? Oh, and by the way, you can enclose blocks of code (or tracebacks) in triple ticks (\``` ... ```)  rather than single ticks to get nicer formatting.

**Comment by sjhend03** [comment]
> The first error is coming from being unable to build the data container. I was getting the second error intermittently this afternoon on LLO, but it went away on its own, so it's a little tough to debug. From some old threads I'm finding online, I think it may be related to running out of RAM. Can you try re-building again? Oh, and by the way, you can enclose blocks of code (or tracebacks) in triple ticks (``` ... ```) rather than single ticks to get nicer formatting.

That seems to be the problem, I changed nodes to one with more memory and built export and data successfully.
