### ISSUE TITLE
Begin saving sorted detection statistic

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframev2#236]
For datasets with a lot of events, sorting the detection statistic (as we do for the `threshold_at_far` calculation) can take a significant amount of time. Does it make sense to pre-calculate the sorting?

**Comment by EthanMarx** [comment]
Thought about this too. The issue is we aggregate the files on the fly. What we could do is aggregate, then load in the full dataset, sort by detection statistic, and write back out.

**Comment by wbenoit26** [comment]
Yeah, I think this would be the way to go. It's about 10 minutes to sort, so not too bad.

**Comment by wbenoit26** [comment]
Closed by #241
