### ISSUE TITLE
Switch waveform approximant

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframev2#261]
Using `pycbc` to generate waveforms, there are some (admittedly unlikely) parts of our waveform parameter space that cause the waveform generation to fail (e.g., `m1 = 100, m2 = 5, z = 2, f_min = 20`). I've been thinking we should lower our minimum frequency for a while now, but even setting it dynamically (as is done in Reed's waveform generation package) doesn't solve the issue. Switching to another approximant, such as `IMRPhenomXPHM`, does solve it.

`IMRPhenomXPHM` is about 30% slower than `IMRPhenomPv2`, which is significant, but perhaps not too bad.

Question: is there a different approximant that we should prefer?

**Comment by EthanMarx** [comment]
I don't think there is any reason we shouldn't switch over to `IMRPhenomXPHM`. Especially since we got some criticism for it in the paper. Now that waveform generation is parallelized the 30% is trivial
