### ISSUE TITLE
Add `aframe-init` flag for existing model

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframev2#274]
Action from the review call: add a `review` mode to the `aframe-init` command that essentially just tests an existing set of weights. The command would look like `poetry run aframe-init offline --directory <run_dir> --mode review --weights <path_to_weights>`. This would do the following:

- Set up a run directory at the specified location
- Copy the existing model weights into the appropriate location in the run directory
- Copy a special set of "review" config files that would be set up to run small-scale testing over both timeslides and zero-lag data. The zero-lag data should contain a real event that we expect to detect, and the timeslides should total not more than a month of background to keep the process relatively quick.

@VasSkliris, @kjtwagner Let me know if you have any comments or corrections!

**Comment by Victoria0414** [comment]
@wbenoit26 thank you!

**Comment by wbenoit26** [comment]
@VasSkliris, @kjtwagner, @Victoria0414 This action should be complete. The instructions for running it are [here](https://github.com/EthanMarx/o4-review/tree/main/aframe/scripts#zero-lag-check). If anything is confusing or if anything breaks, please file an issue!
